### ISSUE TITLE
I don't know if I should come here and ask this question.

### ISSUE THREAD

**Issue by yyhhrr** [garnett1966/Mystery-Mansion#3]
Hello, could you please provide a complete map of game Mystery Mansion?and or Could you provide the 1981 version16 of walkthrough? I am Chinese and I like this game. Thank you.

**Comment by garnett1966** [comment]
Hi yyhhrr, sorry, no, I don't have the full map anymore.  I'm tempted to make one, though.  If I do, I'll post it to this repository.

**Comment by garnett1966** [comment]
Here is a partial map and walkthrough, as posted some years ago by someone who played this port.

https://bluerenga.blog/2011/05/06/mystery-mansion-a-wild-stew/
