### ISSUE TITLE
Two bugs?

### ISSUE THREAD

**Issue by skogtun** [garnett1966/Mystery-Mansion#4]
I think I have found two bugs in your code:
Line 1811: Should the bitwise 'or' (|) be a logical 'or' (||) ?
Line 3990: Should the assignment be a comparison?

**Comment by garnett1966** [comment]
Excellent catches, skogtun!  Thank you.  My apologies for the delay in responding.  I have made the changes and will commit them.

**Comment by garnett1966** [comment]
In my professional life, I always reverse the order of comparisons.  So "if (x = 3)" beccomes "if (3 = x)".  The static syntax checker in the compiler then catches the error immediately.  Unfortunately, that's not what f2c does.  I'm tempted to go back through this code and reverse them all, but I'm afraid that I'd introduce more defects.
